

server:
  port: 8384

spring:
  application:
    name: eureka-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     #defaultZone: http://replica1:8483/eureka/,http://replica2:8583/eureka/  http://Jack:123456@localhost:8385/eureka/,
     defaultZone:  http://localhost:8383/eureka/
