server:
  port: 8386

spring:
  application:
    name: ribbon-service
    zipkin:
      base-url: http://localhost:9411
      sleuth:
        sampler:
          probability: 0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8383/eureka/


service-url:
  user-service: http://user-service

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule


